# Generated by Django 4.0.6 on 2022-08-13 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddingBooksModel',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('booktitle', models.CharField(help_text='tit', max_length=100, null=True)),
                ('authorname', models.CharField(help_text='auth', max_length=100)),
                ('department', models.CharField(help_text='dep', max_length=100)),
                ('publisher', models.CharField(help_text='pub', max_length=100)),
                ('edition', models.CharField(help_text='edi', max_length=100)),
                ('bookphoto', models.ImageField(upload_to='images/')),
                ('status', models.TextField(default='pending')),
            ],
        ),
        migrations.CreateModel(
            name='ViewBooks',
            fields=[
                ('view_id', models.AutoField(primary_key=True, serialize=False)),
                ('librarian_status', models.CharField(default='pending', max_length=50)),
                ('librarian_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='librarianapp.addingbooksmodel')),
                ('stu_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentapp.studentregistermodel')),
            ],
        ),
    ]
