# Generated by Django 4.0.6 on 2022-08-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarianapp', '0003_viewbooks_return_book_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='return_book',
            fields=[
                ('return_id', models.AutoField(primary_key=True, serialize=False)),
                ('stu_id', models.CharField(help_text='stu_id', max_length=500, null=True)),
                ('book_id', models.CharField(help_text='book_id', max_length=500, null=True)),
                ('return_status', models.CharField(default='none', max_length=500)),
                ('return_count', models.CharField(default='0', max_length=500)),
            ],
        ),
    ]
