# Generated by Django 4.0.6 on 2022-08-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarianapp', '0004_return_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return_book',
            name='return_status',
            field=models.CharField(default='pending', max_length=500),
        ),
        migrations.AlterField(
            model_name='viewbooks',
            name='return_book_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
