# Generated by Django 4.0.6 on 2022-08-19 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating3', models.CharField(help_text='rating3', max_length=200, null=True)),
                ('text', models.CharField(help_text='rating3', max_length=200, null=True)),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentapp.studentregistermodel')),
            ],
        ),
    ]
