# Generated by Django 4.0.6 on 2022-08-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_studentfeedbackmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeedbackmodel',
            name='sentiment',
            field=models.CharField(help_text='sentiment', max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='studentfeedbackmodel',
            name='text',
            field=models.CharField(help_text='text', max_length=200, null=True),
        ),
    ]
